// Export utilities for LLMDB
import { LLMModel } from '../data/llm-data';
import { SessionEntry } from './sessionStorage';
import Papa from 'papaparse';

export class ExportManager {
  // Export model comparison to CSV
  static exportModelsToCSV(models: LLMModel[]): string {
    const data = models.map(model => ({
      Name: model.name,
      Provider: model.provider,
      'Context Window': model.contextWindow,
      'Input Cost ($/1M)': model.inputCostPer1M,
      'Output Cost ($/1M)': model.outputCostPer1M,
      'Quality Score': model.qualityScore || 'N/A',
      'MMLU': model.benchmarks?.mmlu || 'N/A',
      'HumanEval': model.benchmarks?.humanEval || 'N/A',
      'Speed': model.benchmarks?.speed || 'N/A',
      'Release Date': model.releaseDate || model.released || 'N/A',
      'Status': model.status?.isNew ? 'NEW' : model.status?.isDeprecated ? 'DEPRECATED' : 'ACTIVE',
    }));

    return Papa.unparse(data);
  }

  // Export session history to CSV
  static exportSessionsToCSV(sessions: SessionEntry[]): string {
    const data = sessions.map(session => ({
      'Date & Time': new Date(session.timestamp).toLocaleString(),
      'Model': session.modelName,
      'Provider': session.provider,
      'Input Tokens': session.inputTokens,
      'Output Tokens': session.outputTokens,
      'Total Tokens': session.totalTokens,
      'Input Cost ($)': session.inputCost.toFixed(6),
      'Output Cost ($)': session.outputCost.toFixed(6),
      'Total Cost ($)': session.totalCost.toFixed(6),
      'Context Usage %': session.contextUsagePercent.toFixed(2),
    }));

    return Papa.unparse(data);
  }

  // Export cost calculation to CSV
  static exportCostCalculationToCSV(calculations: {
    model: LLMModel;
    inputTokens: number;
    outputTokens: number;
    requestsPerDay: number;
    dailyCost: number;
    monthlyCost: number;
  }[]): string {
    const data = calculations.map(calc => ({
      'Model': calc.model.name,
      'Provider': calc.model.provider,
      'Input Tokens per Request': calc.inputTokens,
      'Output Tokens per Request': calc.outputTokens,
      'Requests per Day': calc.requestsPerDay,
      'Daily Cost ($)': calc.dailyCost.toFixed(4),
      'Monthly Cost ($)': calc.monthlyCost.toFixed(2),
      'Input Cost Rate ($/1M)': calc.model.inputCostPer1M,
      'Output Cost Rate ($/1M)': calc.model.outputCostPer1M,
    }));

    return Papa.unparse(data);
  }

  // Export models to JSON
  static exportModelsToJSON(models: LLMModel[]): string {
    return JSON.stringify(models, null, 2);
  }

  // Export sessions to JSON
  static exportSessionsToJSON(sessions: SessionEntry[]): string {
    return JSON.stringify(sessions, null, 2);
  }

  // Export models to Markdown table
  static exportModelsToMarkdown(models: LLMModel[]): string {
    const headers = ['Name', 'Provider', 'Context', 'Input Cost', 'Output Cost', 'Quality Score'];
    const separator = headers.map(() => '---');

    const rows = models.map(model => [
      model.name,
      model.provider,
      model.contextWindow.toLocaleString(),
      `$${model.inputCostPer1M.toFixed(2)}/1M`,
      `$${model.outputCostPer1M.toFixed(2)}/1M`,
      model.qualityScore ? model.qualityScore.toFixed(1) : 'N/A',
    ]);

    const table = [
      `| ${headers.join(' | ')} |`,
      `| ${separator.join(' | ')} |`,
      ...rows.map(row => `| ${row.join(' | ')} |`),
    ].join('\n');

    return table;
  }

  // Generate comprehensive report
  static generateComprehensiveReport(data: {
    models: LLMModel[];
    sessions: SessionEntry[];
    stats: ReturnType<typeof import('./sessionStorage').SessionStorageManager.calculateStats>;
  }): string {
    const { models, sessions, stats } = data;

    const report = `
# LLMDB Usage Report
Generated: ${new Date().toLocaleString()}

## Summary Statistics
- Total Sessions: ${stats.totalSessions}
- Total Tokens Used: ${stats.totalTokens.toLocaleString()}
- Total Cost: $${stats.totalCost.toFixed(4)}
- Average Cost per Session: $${stats.averageCostPerSession.toFixed(6)}
- Average Tokens per Session: ${Math.round(stats.averageTokensPerSession).toLocaleString()}
- Most Used Model: ${stats.mostUsedModel}

## Token Breakdown
- Input Tokens: ${stats.totalInputTokens.toLocaleString()}
- Output Tokens: ${stats.totalOutputTokens.toLocaleString()}

## Selected Models
${this.exportModelsToMarkdown(models)}

## Recent Sessions (Last 10)
${this.exportSessionsToMarkdown(sessions.slice(0, 10))}

---
Report generated by LLMDB - The Ultimate LLM Comparison Tool
`;

    return report;
  }

  // Export sessions to Markdown table
  private static exportSessionsToMarkdown(sessions: SessionEntry[]): string {
    const headers = ['Date', 'Model', 'Tokens', 'Cost', 'Context %'];
    const separator = headers.map(() => '---');

    const rows = sessions.map(session => [
      new Date(session.timestamp).toLocaleDateString(),
      session.modelName,
      session.totalTokens.toLocaleString(),
      `$${session.totalCost.toFixed(6)}`,
      `${session.contextUsagePercent.toFixed(1)}%`,
    ]);

    const table = [
      `| ${headers.join(' | ')} |`,
      `| ${separator.join(' | ')} |`,
      ...rows.map(row => `| ${row.join(' | ')} |`),
    ].join('\n');

    return table;
  }

  // Download helper
  static downloadFile(content: string, filename: string, mimeType: string = 'text/plain'): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // Export with timestamp in filename
  static downloadWithTimestamp(content: string, baseName: string, extension: string, mimeType?: string): void {
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${baseName}-${timestamp}.${extension}`;
    this.downloadFile(content, filename, mimeType);
  }
}
